/**
 * Programmatic mirror of `src/styles/tokens.css`.
 * CSS variables remain the runtime source of truth.
 * These maps are for docs, tests, and non-CSS consumers.
 */

export const primitiveColors = {
  white: "#ffffff",
  slate50: "#f8fafc",
  slate100: "#f1f5f9",
  slate200: "#e2e8f0",
  slate400: "#94a3b8",
  slate500: "#64748b",
  slate800: "#1e293b",
  slate900: "#0f172a",
  slate950: "#020617",
  blue200: "#bfdbfe",
  blue300: "#93c5fd",
  blue400: "#60a5fa",
  blue500: "#3b82f6",
  blue600: "#2563eb",
  blue700: "#1d4ed8",
  blue800: "#1e40af",
  blue900: "#1e3a8a",
  red500: "#ef4444",
  red900: "#7f1d1d",
} as const;

export type PrimitiveColorName = keyof typeof primitiveColors;

export const lightTheme = {
  background: primitiveColors.white,
  foreground: primitiveColors.slate900,
  card: primitiveColors.white,
  cardForeground: primitiveColors.slate900,
  popover: primitiveColors.white,
  popoverForeground: primitiveColors.slate900,
  primary: primitiveColors.blue600,
  primaryForeground: primitiveColors.white,
  primaryHover: primitiveColors.blue500,
  secondary: primitiveColors.slate100,
  secondaryForeground: primitiveColors.slate900,
  muted: primitiveColors.slate100,
  mutedForeground: primitiveColors.slate500,
  accent: primitiveColors.slate100,
  accentForeground: primitiveColors.slate900,
  destructive: primitiveColors.red500,
  destructiveForeground: primitiveColors.white,
  border: primitiveColors.slate200,
  input: primitiveColors.slate200,
  ring: primitiveColors.blue500,
  chart1: primitiveColors.blue600,
  chart2: primitiveColors.blue500,
  chart3: primitiveColors.blue400,
  chart4: primitiveColors.blue300,
  chart5: primitiveColors.blue200,
  sidebar: primitiveColors.slate50,
  sidebarForeground: primitiveColors.slate900,
  sidebarPrimary: primitiveColors.blue600,
  sidebarPrimaryForeground: primitiveColors.white,
  sidebarAccent: primitiveColors.slate100,
  sidebarAccentForeground: primitiveColors.slate900,
  sidebarBorder: primitiveColors.slate200,
  sidebarRing: primitiveColors.blue500,
} as const;

export const darkTheme = {
  background: primitiveColors.slate950,
  foreground: primitiveColors.slate50,
  card: primitiveColors.slate900,
  cardForeground: primitiveColors.slate50,
  popover: primitiveColors.slate900,
  popoverForeground: primitiveColors.slate50,
  primary: primitiveColors.blue500,
  primaryForeground: primitiveColors.white,
  primaryHover: primitiveColors.blue400,
  secondary: primitiveColors.slate800,
  secondaryForeground: primitiveColors.slate50,
  muted: primitiveColors.slate800,
  mutedForeground: primitiveColors.slate400,
  accent: primitiveColors.slate800,
  accentForeground: primitiveColors.slate50,
  destructive: primitiveColors.red900,
  destructiveForeground: primitiveColors.slate50,
  border: primitiveColors.slate800,
  input: primitiveColors.slate800,
  ring: primitiveColors.blue600,
  chart1: primitiveColors.blue500,
  chart2: primitiveColors.blue600,
  chart3: primitiveColors.blue700,
  chart4: primitiveColors.blue800,
  chart5: primitiveColors.blue900,
  sidebar: primitiveColors.slate900,
  sidebarForeground: primitiveColors.slate50,
  sidebarPrimary: primitiveColors.blue500,
  sidebarPrimaryForeground: primitiveColors.white,
  sidebarAccent: primitiveColors.slate800,
  sidebarAccentForeground: primitiveColors.slate50,
  sidebarBorder: primitiveColors.slate800,
  sidebarRing: primitiveColors.blue600,
} as const;

export type SemanticColorName = keyof typeof lightTheme;
